name: game_challenge_2025feb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.23.0
  flame_audio: ^2.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/enemy.png
    - assets/images/stars1.png
    - assets/images/stars2.png
    - assets/images/bullet.png
    - assets/audio/laser.ogg
    - assets/audio/explosion.ogg
    - assets/audio/background_music.mp3
